// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcHelpDesk.Data;

namespace MvcHelpDesk.Migrations
{
    [DbContext(typeof(MvcHelpDeskContext))]
    [Migration("20201126234221_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("MvcHelpDesk.Models.Denunciar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tecnico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Denunciar");
                });

            modelBuilder.Entity("MvcHelpDesk.Models.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentário")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Nota")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("MvcHelpDesk.Models.OrdemDeServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriaServico")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DenunciarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoProblema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeedBackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoServico")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DenunciarId");

                    b.HasIndex("FeedBackId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OrdemDeServico");
                });

            modelBuilder.Entity("MvcHelpDesk.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("MvcHelpDesk.Models.Tecnico", b =>
                {
                    b.HasBaseType("MvcHelpDesk.Models.Usuario");

                    b.Property<string>("Escolaridade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experiencia")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Tecnico");
                });

            modelBuilder.Entity("MvcHelpDesk.Models.OrdemDeServico", b =>
                {
                    b.HasOne("MvcHelpDesk.Models.Denunciar", "Denunciar")
                        .WithMany()
                        .HasForeignKey("DenunciarId");

                    b.HasOne("MvcHelpDesk.Models.FeedBack", "FeedBack")
                        .WithMany()
                        .HasForeignKey("FeedBackId");

                    b.HasOne("MvcHelpDesk.Models.Tecnico", null)
                        .WithMany("AtenderServico")
                        .HasForeignKey("TecnicoId");

                    b.HasOne("MvcHelpDesk.Models.Usuario", null)
                        .WithMany("SolicitarServico")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
